[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v --tb=short --self-contained-html

markers =
    smoke: basic checks
    qaplayground: tests for QA Playground forms
    expandtesting: tests for ExpandTesting login