[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_functions = test_*

addopts =
    -v
    --tb=short
    --alluredir=reports/allure-results
    --clean-alluredir

markers =
    smoke: basic checks
    qaplayground: tests for QA Playground
    expandtesting: tests for ExpandTesting login